development:
  adapter: postgresql
  encoding: unicode
  database: theartscene_development
  pool: 5
  username: theartscene
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: theartscene_test
  pool: 5
  username: theartscene
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: theartscene_production
  pool: 5
  username: theartscene
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_URL'] %>

