defaults: &defaults
  hosts: ['127.0.0.1:9200']
  bootstrap: true

development:
  <<: *defaults
  index: development

test:
  <<: *defaults
  index: test

production:
  <<: *defaults
  index: production
